### ISSUE TITLE
Table of Contents Mouse-over is annoying

### ISSUE THREAD

**Issue by znmeb** [ForJournalism/fj-responsive-design#4]
On desktop Chrome, when I put the mouse at a certain point on the page, a big black Table of Contents comes up. You can't click on any of it, and even if you could, it's annoying to have that thing leap out at you. It won't work on a tablet or phone, which is a relief. This is a course on responsive design ... I assume somewhere later on there's a description of why the 'hover' coding is a bad idea for pages that have to work on both desktops and mobiles. ;-)

**Comment by rwkster** [comment]
I am having a similar issue in all browsers. The hover doesn't stay up unless you click on the title first. And the when I click on the submenu items thinking it will take me to the appropriate chapter/item on the page, it doesn't. In fact, it doesn't do anything.... But it doesn't matter that much because none of the content even shows up in Firefox anyway, and the vimeo videos for Chrome takes so long to buffer I don't have the time to watch them. Maybe some summary text that tells us a little more about what each vid is about at least?

**Comment by gotoplanb** [comment]
Yep. photo-click-and-swap-to-video coming releasing tomorrow. Annotations probably next week.
