### ISSUE TITLE
No content appears; would like refund

### ISSUE THREAD

**Issue by lschneiderman** [ForJournalism/fj-responsive-design#7]

**Comment by gotoplanb** [comment]
Hi @lschneiderman, can you post a link to the URL that is causing trouble? I'm currently moving content into a new framework because our original host/publisher updated their default templates and busted all the FJ pages.

**Comment by lschneiderman** [comment]
Hi, Dave,

Thanks for the quick reply! I was viewing the Responsive Design page:
https://beta.publet.com/for-journalism/responsive-web-design-for-journalism/
.

Best,
Laura

Laura Malt Schneiderman
Web Content Producer
Pittsburgh Post-Gazette
post-gazette.com
412.263.1923

**Comment by gotoplanb** [comment]
@lschneiderman Ok, I don't have all of the content moved yet (or designed well) but at least this will get you started: http://forjournalism.github.io/courses/responsive-design/ 

I'll try to get the rest of the content ported to GitHub Pages over the next week for this course. 

I also refunded the purchase price, since the content is going to be free as in beer.

**Comment by lschneiderman** [comment]
Thank  you!

Laura Malt Schneiderman
Web Content Producer
Pittsburgh Post-Gazette
post-gazette.com
412.263.1923
